# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
