# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_stock_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='tracker.Stock'),
        ),
    ]
