# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170903_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='added_on',
        ),
        migrations.AlterField(
            model_name='stock',
            name='modified_on',
            field=models.DateField(),
        ),
    ]
