# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170909_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
