# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_price_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='delivery',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
