# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_price_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
